//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class videoproducer
    {
        public int videoproducer_id { get; set; }
        public int videoproducer_id_producer { get; set; }
        public int videoproducer_id_video { get; set; }
    
        public virtual producer producer { get; set; }
        public virtual video video { get; set; }
    }
}
