//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VideoRentalSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class videolist
    {
        public int videolist_id { get; set; }
        public int videolist_id_order { get; set; }
        public int videolist_id_video { get; set; }
        public Nullable<int> videolist_quantity { get; set; }
    
        public virtual order order { get; set; }
        public virtual video video { get; set; }
    }
}
