//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VideoRentalSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class video
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public video()
        {
            this.videoproducer = new HashSet<videoproducer>();
            this.videogenre = new HashSet<videogenre>();
            this.videolist = new HashSet<videolist>();
        }
    
        public int video_id { get; set; }
        public string video_name { get; set; }
        public int video_year { get; set; }
        public string video_description { get; set; }
        public double video_price_per_day { get; set; }
        public int video_quantity { get; set; }
        public string video_cover_url { get; set; }
        public string video_country { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<videoproducer> videoproducer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<videogenre> videogenre { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<videolist> videolist { get; set; }
    }
}
