//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VideoRentalSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class videogenre
    {
        public int videogenre_id { get; set; }
        public Nullable<int> videogenre_id_genre { get; set; }
        public Nullable<int> videogenre_id_video { get; set; }
    
        public virtual genre genre { get; set; }
        public virtual video video { get; set; }
    }
}
